# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Learning Project
on:
  workflow_dispatch: # triggered manually

permissions:
  contents: read

jobs:
  build:

    runs-on: [self-hosted, Tobis-runner]

    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v2
    - uses: docker/build-push-action@v4
      with:
        context: .
        file: "Dockerfile.test"
        tags: BasicDocker
        load: true
        cache-from: type=gha
        cache-to: type=gha, mode=max
        push: false
    - name: Run Python Container
      uses: addnab/docker-run-action@v3
      with:
        image: localpytest:latest
        run: dir  
  
    
    # - name: Set up Python 3.10
    #   uses: actions/setup-python@v3
    #   with:
    #     python-version: "3.10"
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip pytest flake8
    # - name: Lint with flake8
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    # - name: Test with pytest
    #   run: |
